### ISSUE TITLE
react-router-dom is not working

### ISSUE THREAD

**Issue by ahmedrowaihi** [uidb-dev/react.cordova#26]
when I run the app through Serve it's working fine, but after building an Apk I guess react-router-dom is not working.. please guys I need guidance

**Comment by ahmedrowaihi** [comment]
Android Please guys help!!

**Comment by orchoban** [comment]
Did you try to work with https://www.npmjs.com/package/react.cordova-navigation_controller
?

**Comment by agpl** [comment]
Have you tried to use HashRouter? Recent cordova-android@10 would support standard router implementation also.

**Comment by orchoban** [comment]
> Have you tried to use HashRouter? Recent cordova-android@10 would support standard router implementation also.

Yes, it is have to work.
See example:
https://github.com/orchoban/react.cordova-navigation_controller/issues/19#issuecomment-950731798

**Comment by ahmedrowaihi** [comment]
I left cordova, it seemed terrible, I am happy with RN.
