### ISSUE TITLE
Reco: error on npm run start

### ISSUE THREAD

**Issue by rick-appart** [uidb-dev/react.cordova#33]
First i installed `sudo npm install -g react.cordova`
Then i initalized the project `reco init com.example.hello "recotest"` with a empty template

On `npm run start` i get this error

**_Compiled with problems:X
ERROR in ./src/index.js 9:0-24
Module not found: Error: Can't resolve 'cordova_script' in 'D:\code\Tests\recotest\src'_**

I did not change the code.

**Comment by orchuban** [comment]
try `npm i cordova_script`

**Comment by rick-appart** [comment]
I needed to force installed but it worked, weird that it needs that. But its fixed.
